### ISSUE TITLE
Be aware of docker caching

### ISSUE THREAD

**Issue by DatMayo** [eisengrind/docker-altv-server#1]
Docker is a great tool, but its sometimes tricky. So docker will cache your Dockerfile, if the file is not changed you'll stick with i.e. Server build #123 even if #234 is out. To get around this issue you MUST use `--no-cache`.

**Comment by pixlcrashr** [comment]
Thanks for the reminder. Indeed, thats correct.

But the caching "problem" does not occur, if you are using specific Docker image tags.

Say, if you are using a Dockerfile starting with

```Dockerfile
FROM eisengrind/altv-server:release
...
```

then of course, the Dockerfile will not recognize it as a change if there was an update. The reason for this is - as you mentioned - that the local Docker deamon sees that a local image `eisengrind/altv-server:release` already exists and thus it does not pull the image again.

That is why the Docker image provides build-specific tags such as `1153-dotnet` (for the latest release) etc. . Then caching makes sense again, because the image tag `1153` is not meant to be changed in the future.

See this example:

```Dockerfile
FROM eisengrind/altv-server:1153
```

One would have to change the build number when an update of the alt:V server is intended.

I'll add a note for building with `Dockerfile`s
