### ISSUE TITLE
Failed to load "js-module.so"

### ISSUE THREAD

**Issue by leNicDev** [eisengrind/docker-altv-server#33]
When starting a fresh server, I get the following error message:
`[Error] Failed to load "js-module.so", Unix error: libnode.so.108: cannot open shared object file: No such file or directory`

Steps to reproduce:
`docker run -it --rm eisengrind/altv-server:release`

After some analysis I noticed there is no `js-module.so` in `/opt/altv/modules`. Instead there is a directory called `js-module` containing three files:
- libjs-bytecode-module.so
- libjs-module.so
- libnode.so.102

**Comment by pixlcrashr** [comment]
@leNicDev What was exactly wrong in the PR? Every now and then, the alt:V team updates libnode, so we get a new version number. If that is the case, I ofc will update the repo - since it would mean that the public Docker image is broken.

For this, we just have to change `ARG LIBNODE_VERSION=102` to the required version. If you want to do that, let me know.

EDIT: the current libnode version should be 108, then.

**Comment by pixlcrashr** [comment]
@leNicDev New images should be built in a second. See https://github.com/eisengrind/docker-altv-server/actions/runs/4947690768/jobs/8847407955 for reference.
