### ISSUE TITLE
server.cfg resets on start

### ISSUE THREAD

**Issue by killer-kirito** [eisengrind/docker-altv-server#8]
Hey, 
Ive just used your c# + js module start up, and linked the modules, resources, data, and the server.cfg to my storage, 
The problem is on startup the server resets the server.cfg, 
Is there anyway to get that to work ?

**Comment by pixlcrashr** [comment]
Well, the key problem you have is that this Docker image creates the `server.cfg` file when the containers starts. Due to the design of containers being stateless, this is an important requirement.

However, you can either create an own image based off this one or you simply use the environment variables from which the `server.cfg` is created. For that, see the environment variables in this shell script: [https://github.com/eisengrind/docker-altv-server/blob/master/.docker/scripts/entrypoint.sh](https://github.com/eisengrind/docker-altv-server/blob/master/.docker/scripts/entrypoint.sh) . You simply provide the environment variables with your values when you start your container using your preferred way of starting (Docker, Docker-Compose, K8s, ...).

Documentation will be added sometime for using the environment variables.

**Comment by pixlcrashr** [comment]
No answer. Closing.
